version: '3.9'
services:
  sport-story-server-app:
    container_name: sport-story-server-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
    command: sh -c "npm run typeorm:migrate && npm start"

  postgres:
    container_name: sport_hub_postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: sport_hub
    ports:
      - "6543:5432"