version: '3.9'
services:
  sport-story-server-app:
    container_name: sport-story-server-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    command: sh -c "npm start"