version: "3.9"
services:
  postgres:
    container_name: sport_hub_postgres
    image: postgres
    env_file:
      - .env
    ports:
      - "7654:5432"

  server_app:
    container_name: sport_hub_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    restart: on-failure
    command: sh -c "npm run typeorm:migrate && npm run production"

  web_app:
    container_name: sport_hub_web
    build:
      context: .
      dockerfile: ./webapp/Dockerfile
    volumes:
      - ./webapp/dist:/app/webapp/dist
    command: sh -c "npm run webapp:build"

  nginx:
    container_name: sport_hub_nginx
    image: nginx:latest
    volumes:
      - ./webapp/dist:/app/dist
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "82:80"
      - "445:443"
    depends_on:
      - server_app
      - web_app

  certbot:
    container_name: sport_hub_certbot
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt/:rw
      - ./data/certbot/www:/var/www/certbot/:rw
