name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display the path
      run: pwd
      shell: bash

    - name: Pull latest changes
      run: git pull origin main

    - name: Stop Docker Compose services
      run: docker-compose down

    - name: Build and start Docker Compose services
      run: docker-compose up --build -d
