name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v1.0.3
            
      with:
        host: 159.223.15.127
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/sport-story-hub-bot
          git pull origin main
          cat package.json
          npm run docker:stop
          npm run docker:clean
          npm run docker:prod
